language: bash
services: docker

env:
  - MYSQL_VERSION=8.0 DISTRIB=''
  - MYSQL_VERSION=5.7 DISTRIB=''
  - MYSQL_VERSION=5.6 DISTRIB=''
  - MYSQL_VERSION=5.5 DISTRIB=''
  - MYSQL_VERSION=5.7 DISTRIB='ubuntu'

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$MYSQL_VERSION/$DISTRIB"
  - image="mysql:${MYSQL_VERSION}${DISTRIB}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
