# add this file
# default MySQL root password is 123456

version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: redmine-mysql
    restart: always
    ports:
     - 3306:3306
    volumes:
     - ./mysql_config/conf.d:/etc/mysql/conf.d
     - ./mysql_data:/var/lib/mysql
     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456

      
networks:
  default:
      name: "apps"
